name: pubmed-search
 
channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.11
  - jupyterlab=4.0.1
  - pandas=2.0.3
  - beautifulsoup4=4.12.2
  - requests=2.31.0
  - tqdm=4.66.1 
  - lxml=4.9.3 